//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtpProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanovi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clanovi()
        {
            this.Posudbe = new HashSet<Posudbe>();
        }
    
        public string clanskiBroj { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string telefonskiBroj { get; set; }
        public string adresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posudbe> Posudbe { get; set; }
    }
}
