//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtpProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knjige
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knjige()
        {
            this.Posudbe = new HashSet<Posudbe>();
        }
    
        public string NazivKnjige { get; set; }
        public string Kategorija { get; set; }
        public int Količina { get; set; }
        public string ISBN { get; set; }
        public string Autor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posudbe> Posudbe { get; set; }
    }
}
