//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posudbe
    {
        public int Id { get; set; }
        public string isbnKnjige { get; set; }
        public Nullable<System.DateTime> datumPosudbe { get; set; }
        public Nullable<System.DateTime> datumPovratka { get; set; }
        public string clanskiBroj { get; set; }
    
        public virtual Clanovi Clanovi { get; set; }
        public virtual Knjige Knjige { get; set; }
    }
}
